/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_ralala_sshd_net_ptm_NativeProcessPTM */

#ifndef _Included_fr_ralala_sshd_net_ptm_NativeProcessPTM
#define _Included_fr_ralala_sshd_net_ptm_NativeProcessPTM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_ralala_sshd_net_ptm_NativeProcessPTM
 * Method:    create0
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Lfr/ralala/sshd/net/ptm/NativeProcessPTM;
 */
JNIEXPORT jobject JNICALL Java_fr_ralala_sshd_net_ptm_NativeProcessPTM_create0
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

/*
 * Class:     fr_ralala_sshd_net_ptm_NativeProcessPTM
 * Method:    waitFor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fr_ralala_sshd_net_ptm_NativeProcessPTM_waitFor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
